version: '3.8'

services:
  node:
    container_name: node
    image: lucastheiss31/nodecontainer:latest
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - .env
    command: npm start


  java:
    container_name: java
    image: lucastheiss31/webjavav2:latest
    pull_policy: always
    ports:
      - "3001:8080"
    env_file:
      - .env
    
  dotnet:
    container_name: dotnet
    image: lucastheiss31/aspnetapp:latest
    pull_policy: always
    ports:
      - "3002:80"
    

  django:
    container_name: django
    image: lucastheiss31/djangocontainer:latest
    pull_policy: always
    ports:
      - "3003:8000"
    env_file:
      - .env