version: '3.8'

services:
  node:
    image: lucastheiss31/nodecontainer:latest
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - .env
    command: npm start


  java:
    image: lucastheiss31/webjavav2:latest
    pull_policy: always
    ports:
      - "3001:8080"

  dotnet:
    image: lucastheiss31/aspnetapp:latest
    pull_policy: always
    ports:
      - "3002:80"
    

