version: '3.8'

services:
  web:
    image: lucastheiss31/nodecontainer:latest
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: npm start

services:
  java:
    build:
      image: lucastheiss31/webjavav2:latest
      pull_policy: always
      ports:
        - "3001:8080"
      environment:
        JAVA_ENV: development
      command: npm start
