version: '3.8'

services:
  web:
    image: lucastheiss31/nodecontainer:latest
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: npm start