version: '3'
services:  
  nginx:    
    container_name: "nginx"    
    image: nginx:latest    
    ports:      
      - "80:80"    
    network_mode: "host"    
    volumes:      
      - /etc/letsencrypt/live/www.status200.sol.app.br/fullchain.pem:/cert/certificate.pem      
      - /etc/letsencrypt/live/www.status200.sol.app.br/privkey.pem:/cert/key.pem      
      - ./nginx.conf:/etc/nginx/conf.d/default.conf