version: '3'
services:  
  nginx:    
    container_name: "nginx"    
    image: nginx:latest    
    ports:      
      - "80:80"    
    network_mode: "host"    
    volumes:      
      - /etc/letsencrypt/live/www.status200.sol.app.br/fullchain.pem:/cert/certificate.pem      
      - /etc/letsencrypt/live/www.status200.sol.app.br/privkey.pem:/cert/key.pem
      - /etc/letsencrypt/live/node.status200.sol.app.br/fullchain.pem:/cert/node.certificate.pem
      - /etc/letsencrypt/live/node.status200.sol.app.br/privkey.pem:/cert/node.key.pem
      - /etc/letsencrypt/live/java.status200.sol.app.br-0001/fullchain.pem:/cert/node.certificate.pem
      - /etc/letsencrypt/live/java.status200.sol.app.br-0001/privkey.pem:/cert/node.key.pem
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
