name: Build e deploy do load balancer

# Ativa o workflow apenas em alterações no diretório nginx na branch main
on:
  push:
    branches:
      - main
    paths:
      - 'nginx/**'
env:
  DEPLOY_DIR: /projeto-lightsail # Localização dos arquivos do projeto no servidor

jobs:
  ssh-and-run-nginx:
    runs-on: ubuntu-latest

    # Faz SSH no servidor, usa git pull para atualizar os arquivos e em seguida sobe o container do nginx novamente.
    steps:
      - name: Deploy no servidor usando SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LB_HOST }}
          username: ${{ secrets.ACTIONS_USER }}
          key: ${{ secrets.ACTIONS_KEY }}
          port: ${{ secrets.LB_PORT }}
          script: |
            cd ${{ env.DEPLOY_DIR }} 
            git pull
            sudo docker-compose up -d
            sudo docker image prune -a -f
