name: Build e deploy de aplicação Node

on:
  push:
    branches:
      - main
    paths:
      - 'node/**'
env:
  IMAGE_NAME: lucastheiss31/nodecontainer
  DEPLOY_DIR: /projeto-lightsail

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extrair metadados a partir do repo
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Login no Registro de Containers do Devopstools
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v3
        with:
          context: node
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy no servidor usando SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.APPS_HOST }}
          username: ${{ secrets.ACTIONS_USER }}
          key: ${{ secrets.ACTIONS_KEY }}
          port: ${{ secrets.APPS_PORT }}
          script: |
            cd ${{ env.DEPLOY_DIR }} 
            sudo docker-compose up -d node
            sudo docker image prune -a -f